package com.tcs.sgv.dcps.valueobject;

// default package
// Generated Mar 12, 2012 1:10:04 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.tcs.sgv.dcps.valueobject.MstDcpsBillGroup;

/**
 * RltDcpsBillGroupMpg generated by hbm2java
 */
public class RltDcpsBillGroupMpg implements java.io.Serializable
{

	private long rltDcpsBillGroupId;
	private MstDcpsBillGroup mstDcpsBillGroup;
	private Date fromDate;
	private Date toDate;
	private String orderNo;
	private Date orderDate;

	public RltDcpsBillGroupMpg()
	{}

	public RltDcpsBillGroupMpg(long rltDcpsBillGroupId, MstDcpsBillGroup mstDcpsBillGroup)
	{
		this.rltDcpsBillGroupId = rltDcpsBillGroupId;
		this.mstDcpsBillGroup = mstDcpsBillGroup;
	}

	public RltDcpsBillGroupMpg(long rltDcpsBillGroupId, MstDcpsBillGroup mstDcpsBillGroup, Date fromDate, Date toDate, String orderNo, Date orderDate)
	{
		this.rltDcpsBillGroupId = rltDcpsBillGroupId;
		this.mstDcpsBillGroup = mstDcpsBillGroup;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.orderNo = orderNo;
		this.orderDate = orderDate;
	}

	public long getRltDcpsBillGroupId()
	{
		return this.rltDcpsBillGroupId;
	}

	public void setRltDcpsBillGroupId(long rltDcpsBillGroupId)
	{
		this.rltDcpsBillGroupId = rltDcpsBillGroupId;
	}

	public MstDcpsBillGroup getMstDcpsBillGroup()
	{
		return this.mstDcpsBillGroup;
	}

	public void setMstDcpsBillGroup(MstDcpsBillGroup mstDcpsBillGroup)
	{
		this.mstDcpsBillGroup = mstDcpsBillGroup;
	}

	public Date getFromDate()
	{
		return this.fromDate;
	}

	public void setFromDate(Date fromDate)
	{
		this.fromDate = fromDate;
	}

	public Date getToDate()
	{
		return this.toDate;
	}

	public void setToDate(Date toDate)
	{
		this.toDate = toDate;
	}

	public String getOrderNo()
	{
		return this.orderNo;
	}

	public void setOrderNo(String orderNo)
	{
		this.orderNo = orderNo;
	}

	public Date getOrderDate()
	{
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate)
	{
		this.orderDate = orderDate;
	}

}
